

default_platform(:android)

platform :android do
  desc "lane for android firebase app distribution"
  lane :firebase_distribution do
    sh "flutter clean"
    sh "flutter build apk --release --flavor  Production --target lib/main_production.dart --no-tree-shake-icons"
    firebase_app_distribution(
      app: "1:732524681454:android:daa8f48f40f94d2c03bbff",
      firebase_cli_token: ENV['FIREBASE_CLI_TOKEN'],
      android_artifact_type: "APK",
      android_artifact_path: "../build/app/outputs/flutter-apk/app-production-release.apk",
      testers: "asmaaelsaeed39@gmail.com",
      release_notes: "This is a first githup fastlane firebase app distribution to test release for the Android app."
    )
  end  
end
