name: Android GitHup Action Firebase App Distribution Workflow

# This workflow is triggered on pushes to the main branch and uses Fastlane to build and distribute an Android app apk via Firebase App Distribution.

on:
  push:
    branches:
      - main

jops:
  distribute_to_firebasse:
    runs-on: ubuntu-latest
    steps:
      - name: checkout my repo codes
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: setup ruby 
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4.5'
          bundler-cache: true
          working-directory: android

      - name: Build and distribute the app
        env:
          FIREBASE_CLI_TOKEN: ${{ secrets.FIREBASE_CLI_TOKEN }}
        run: |
          bundle exec fastlane android firebase_distribution
        working-directory: android
        
